#!/bin/zsh

filename=` sed -n '/file/p' $HOME/.config/nitrogen/bg-saved.cfg `
filename=`echo ${filename/file=/}`
cd $HOME/Scripts/gvcci-source
./gvcci.sh $filename --template $HOME/.gvcci/templates --symlink-wallpaper --background dark
cd

filename=`basename $filename`
filename=`echo ${filename/.jpg/}`
filename=`echo ${filename/.png/}`

cp $HOME/.gvcci/themes/$filename/xresources ~/.Xresources && echo "writing Xresources file..."
xrdb ~/.Xresources && echo "reloading Xresources file..."
echo "done"
