#!/bin/sh
#
# ufetch-ubuntu - tiny system info for ubuntu

## INFO

# user is already defined
host="$(hostname)"
os="$(lsb_release -ds)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(dpkg -l | wc -l)"
shell="$(basename "$SHELL")"

## UI DETECTION

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -f "${HOME}/.xinitrc" ]; then
	ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	uitype='WM'
elif [ -f "${HOME}/.xsession" ]; then
	ui="$(tail -n 1 "${HOME}/.xsession" | cut -d ' ' -f 2)"
	uitype='WM'
else
	ui='unknown'
	uitype='UI'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	black2="$(tput setaf 8)"
	red="$(tput setaf 1)"
	red2="$(tput setaf 9)"
  green="$(tput setaf 2)"
	green2="$(tput setaf 10)"
	yellow="$(tput setaf 3)"
	yellow2="$(tput setaf 11)"
	blue="$(tput setaf 4)"
	blue2="$(tput setaf 12)"
	magenta="$(tput setaf 5)"
	magenta2="$(tput setaf 13)"
	cyan="$(tput setaf 6)"
	cyan2="$(tput setaf 14)"
	white="$(tput setaf 7)"
	white2="$(tput setaf 15)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${yellow}"       # labels
nc="${reset}${bold}${blue}"       # user and hostname
ic="${reset}"                       # info
c0="${reset}${yellow}"              # first color

## OUTPUT

# ${nc}${USER}${ic}@${nc}${host}${reset}
cat <<EOF
${red}█${ic}${red2}█${ic} ${lc}OS:        ${ic}${os}${reset}
${green}█${ic}${green2}█${ic} ${lc}KERNEL:    ${ic}${kernel}${reset}
${yellow}█${ic}${yellow2}█${ic} ${lc}UPTIME:    ${ic}${uptime}${reset}
${blue}█${ic}${blue2}█${ic} ${lc}PACKAGES:  ${ic}${packages}${reset}
${magenta}█${ic}${magenta2}█${ic} ${lc}SHELL:     ${ic}${shell}${reset}
${cyan}█${ic}${cyan2}█${ic} ${lc}${uitype}:        ${ic}${ui}${reset}
EOF
